
import React, { useState } from 'react';
import { Layout } from './components/Layout';
import { AdLibForm } from './components/AdLibForm';
import { AdLibDisplay } from './components/AdLibDisplay';
import { AppState, ArtistStyle } from './types';
import { generateAdLibs } from './services/gemini';

const App: React.FC = () => {
  const [state, setState] = useState<AppState>({
    lyrics: '',
    style: ArtistStyle.TRAP,
    loading: false,
    result: null,
    error: null,
  });

  const handleGenerate = async () => {
    if (!state.lyrics.trim()) return;

    setState(prev => ({ ...prev, loading: true, error: null }));
    try {
      const result = await generateAdLibs(state.lyrics, state.style);
      setState(prev => ({ ...prev, loading: false, result }));
      // Scroll to result on mobile
      if (window.innerWidth < 768) {
        setTimeout(() => {
           window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
        }, 100);
      }
    } catch (err: any) {
      setState(prev => ({ ...prev, loading: false, error: err.message }));
    }
  };

  const handleReset = () => {
    setState({
      lyrics: '',
      style: ArtistStyle.TRAP,
      loading: false,
      result: null,
      error: null,
    });
  };

  return (
    <Layout>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Form */}
        <div className="lg:col-span-5 space-y-6">
          <div className="space-y-2">
            <h2 className="text-3xl font-black text-white tracking-tight">
              Craft the Perfect <span className="text-purple-500">Energy.</span>
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed max-w-md">
              Level up your tracks with context-aware ad-libs generated by AI. 
              Our producer-trained model analyzes your bars and finds the perfect pockets for background vocals.
            </p>
          </div>

          <AdLibForm
            lyrics={state.lyrics}
            style={state.style}
            onLyricsChange={(lyrics) => setState(prev => ({ ...prev, lyrics }))}
            onStyleChange={(style) => setState(prev => ({ ...prev, style }))}
            onSubmit={handleGenerate}
            isLoading={state.loading}
          />

          {state.error && (
            <div className="p-4 bg-red-900/20 border border-red-500/50 rounded-xl text-red-400 text-sm flex items-center">
              <i className="fas fa-triangle-exclamation mr-3 text-lg"></i>
              {state.error}
            </div>
          )}

          {state.result && (
            <button
              onClick={handleReset}
              className="w-full py-3 text-zinc-500 hover:text-white transition-colors text-sm font-semibold flex items-center justify-center space-x-2"
            >
              <i className="fas fa-rotate-left"></i>
              <span>Start New Project</span>
            </button>
          )}
        </div>

        {/* Right Column: Display / Result */}
        <div className="lg:col-span-7">
          {state.result ? (
            <AdLibDisplay result={state.result} />
          ) : (
            <div className="h-full min-h-[400px] border-2 border-dashed border-zinc-800 rounded-3xl flex flex-col items-center justify-center text-center p-12 space-y-6 bg-zinc-900/20">
              <div className="w-20 h-20 rounded-full bg-zinc-900 border border-zinc-800 flex items-center justify-center text-zinc-700 text-3xl">
                <i className="fas fa-compact-disc fa-spin-slow"></i>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-bold text-zinc-500">No session active</h3>
                <p className="text-zinc-600 text-sm max-w-xs mx-auto">
                  Paste your bars on the left and choose a style to begin the engineering process.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
};

export default App;
